language: node_js
node_js:
  - "10"
install:
  - npm install
  - npm run build-prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master